#!/usr/bin/env bash
set -euo pipefail

GPU_ID="${1:-${CUDA_VISIBLE_DEVICES:-2}}"
TS_RAW="${2:-$(date +%Y%m%d_%H%M%S)}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_ROOT="${SCRIPT_DIR}"
export SERVER_ROOT

export STRUCTURED_GT_PATH="${STRUCTURED_GT_PATH:-${SERVER_ROOT}/annotations/msvd_structured_train_api_scenehint.json}"
export INIT_CAPTION_CKPT="${INIT_CAPTION_CKPT:-/mnt/sda/Disk_D/zhangwei/projects/VC/project/structured_caption/runs/local_noleak_api_structv2_e8_a/msvd_structured_api_structv2_e8_a_20260303_010342/checkpoints/epoch_003.pt}"

export EPOCHS="${EPOCHS:-3}"
export BATCH_SIZE="${BATCH_SIZE:-48}"
export ACCUM_STEPS="${ACCUM_STEPS:-1}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export RUN_NAME_SUFFIX="${RUN_NAME_SUFFIX:-sceneplus_compact_scenehint_s10_3e}"

export PHRASE_MEMORY_MODE="${PHRASE_MEMORY_MODE:-pooled}"
export PHRASE_TARGET_MODE="${PHRASE_TARGET_MODE:-slot}"
export PHRASE_SLOT_SCHEMA="${PHRASE_SLOT_SCHEMA:-typed_rich_roleaware_sceneplus}"
export MAX_PHRASE_SLOTS="${MAX_PHRASE_SLOTS:-10}"
export PHRASE_SLOT_MAX_LEN="${PHRASE_SLOT_MAX_LEN:-24}"
export PHRASE_INCLUDE_ATTR_UNITS="${PHRASE_INCLUDE_ATTR_UNITS:-0}"
export PHRASE_INCLUDE_SCENE_UNITS="${PHRASE_INCLUDE_SCENE_UNITS:-1}"
export PHRASE_INCLUDE_VIDEO_PHRASE_UNITS="${PHRASE_INCLUDE_VIDEO_PHRASE_UNITS:-0}"
export PHRASE_INCLUDE_VIDEO_ATTR_UNITS="${PHRASE_INCLUDE_VIDEO_ATTR_UNITS:-0}"
export PHRASE_INCLUDE_VIDEO_SCENE_UNITS="${PHRASE_INCLUDE_VIDEO_SCENE_UNITS:-0}"

export LAMBDA_SCENE="${LAMBDA_SCENE:-0.0}"
export LAMBDA_PHRASE="${LAMBDA_PHRASE:-0.02}"
export LAMBDA_PHRASE_GEN="${LAMBDA_PHRASE_GEN:-0.20}"
export LAMBDA_PHRASE_PRED_GEN="${LAMBDA_PHRASE_PRED_GEN:-0.0}"
export PHRASE_PRED_GEN_START_EPOCH="${PHRASE_PRED_GEN_START_EPOCH:-1}"
export LAMBDA_PHRASE_SLOT_PRESENCE="${LAMBDA_PHRASE_SLOT_PRESENCE:-0.10}"
export LAMBDA_PHRASE_BRIDGE="${LAMBDA_PHRASE_BRIDGE:-0.05}"

export PHRASE_SLOT_PLANNER_ENABLE="${PHRASE_SLOT_PLANNER_ENABLE:-1}"
export PHRASE_SLOT_PLANNER_FLOW_ENABLE="${PHRASE_SLOT_PLANNER_FLOW_ENABLE:-0}"
export PHRASE_SLOT_GUIDANCE_ENABLE="${PHRASE_SLOT_GUIDANCE_ENABLE:-1}"
export PHRASE_SLOT_PRESENCE_ENABLE="${PHRASE_SLOT_PRESENCE_ENABLE:-1}"
export PHRASE_SLOT_PRESENCE_SUPPORT_ENABLE="${PHRASE_SLOT_PRESENCE_SUPPORT_ENABLE:-1}"
export PHRASE_SLOT_PRESENCE_EVIDENCE_ENABLE="${PHRASE_SLOT_PRESENCE_EVIDENCE_ENABLE:-1}"
export PHRASE_SLOT_PRESENCE_THRESHOLD="${PHRASE_SLOT_PRESENCE_THRESHOLD:-0.50}"
export PHRASE_SLOT_PRESENCE_CONTEXT_SLOT_TYPES="${PHRASE_SLOT_PRESENCE_CONTEXT_SLOT_TYPES:-subject_modifier,object_modifier,relation_detail,instrument_detail,scene_context}"

export PHRASE_CONDITION_ENABLE="${PHRASE_CONDITION_ENABLE:-1}"
export PHRASE_CONDITION_SLOT_AWARE_ENABLE="${PHRASE_CONDITION_SLOT_AWARE_ENABLE:-0}"
export PHRASE_CONDITION_SLOT_SELECTIVE_ENABLE="${PHRASE_CONDITION_SLOT_SELECTIVE_ENABLE:-0}"
export PHRASE_CONDITION_SLOT_RESIDUAL_ENABLE="${PHRASE_CONDITION_SLOT_RESIDUAL_ENABLE:-1}"
export PHRASE_CONDITION_SLOT_RESIDUAL_SCALE="${PHRASE_CONDITION_SLOT_RESIDUAL_SCALE:-0.12}"
export PHRASE_CONDITION_SLOT_RESIDUAL_SLOT_TYPES="${PHRASE_CONDITION_SLOT_RESIDUAL_SLOT_TYPES:-subject_entity,subject_action,object_entity,object_passive,subject_modifier,object_modifier,relation_detail,scene_context}"
export PHRASE_CONDITION_CANDIDATE_BIAS_ENABLE="${PHRASE_CONDITION_CANDIDATE_BIAS_ENABLE:-1}"
export PHRASE_CONDITION_CANDIDATE_BIAS_SCALE="${PHRASE_CONDITION_CANDIDATE_BIAS_SCALE:-0.08}"
export PHRASE_CONDITION_CANDIDATE_TOPK="${PHRASE_CONDITION_CANDIDATE_TOPK:-16}"
export PHRASE_CONDITION_CANDIDATE_SLOT_TYPES="${PHRASE_CONDITION_CANDIDATE_SLOT_TYPES:-subject_entity,object_entity,subject_modifier,object_modifier,scene_context}"
export PHRASE_CONDITION_TRAIN_USE_PREDICTED="${PHRASE_CONDITION_TRAIN_USE_PREDICTED:-1}"

bash "${SERVER_ROOT}/run_structured_phrase_mainline.sh" D "${GPU_ID}" "${TS_RAW}"
